[package]
name = "pragma"
version = "0.1.0"
cairo-version = "2.0.0-rc5"

[lib]
name = "pragma"

[dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
cubit = { git = "https://github.com/influenceth/cubit" }
starknet = ">=2.0.0-rc5"

[[target.starknet-contract]]

[scripts]
gen-project = "sh scripts/generate_cairo_project.sh"
sierra = "cairo-compile . -r"
test-cairo = "cairo-test --starknet ."

