[project]
protostar-version = "0.13.0"
lib-path = "lib"
linked-libraries = ["account", "introspection", "admin", "publisher_registry","entry", "oracle", "summary_stats", "upgradeable"]

[contracts]
oracle = ["oracle/src"]
account = ["account/src"]
introspection = ["introspection/src"]
admin = ["admin/src"]
publisher_registry = ["publisher_registry/src"]
summary_stats = ["summary_stats/src"]
upgradeable=["upgradeable/src"]
