[project]
protostar-version = "0.12.0"
lib-path = "lib"
linked-libraries = ["account", "introspection", "admin", "publisher_registry"]

[contracts]
account = ["account/src"]
introspection = ["introspection/src"]
admin = ["admin/src"]
publisher_registry = ["publisher_registry/src"]
entry = ["entry/src"]
