[project]
protostar-version = "0.11.0"
lib-path = "lib"
linked-libraries = ["account", "introspection", "admin", "publisher_registry", "entry"]

[contracts]
account = ["account"]
introspection = ["introspection"]
admin = ["admin"]
publisher_registry = ["publisher_registry"]
entry = ["entry"]
