[package]
name = "pragma"
version = "0.1.0"

[dependencies]
account = { path = "account" }
admin = { path = "admin" }
introspection = { path = "introspection" }
publisher_registry = { path = "publisher_registry" }
summary_stats = { path = "summary_stats" }
oracle = { path = "oracle" }
entry = { path = "entry" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
upgradeable = { path = "upgradeable"}
