name: Tests
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pragma-oracle
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
      - run: scarb fmt --check
      - run: scarb test
