name: Run scripts

on: pull_request

jobs: 
  run_scripts: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      # Install Katana
      - name: Install Katana
        run: |
          curl -L https://install.dojoengine.org | bash

      # Debugging: List contents of the installation directory
      - name: List installation directory
        run: |
          ls -la $HOME/.local/bin

      # Update Dojo
      - name: Update Dojo
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          dojoup
      - uses: actions/checkout@v3
      - name: Make script executable
        run: chmod +x scripts/katana.sh


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"


      - name: Run Katana and scripts
        run: bash scripts/katana.sh
