name: Run scripts

on: pull_request

jobs:
  run_scripts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pragma-deployer

    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dojoup
        run: |
          curl -L https://install.dojoengine.org | bash
          echo "$HOME/.config/.dojo/bin" >> $GITHUB_PATH

      - name: Install dojo
        run: |
          dojoup -v v1.0.0-alpha.2
          sudo mv $HOME/.config/.dojo/bin/katana /usr/local/bin/

      - name: Make script executable
        run: chmod +x scripts/katana.sh

      - name: Set up Python and install Poetry
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1

      - name: Build with Scarb
        run: scarb build

      - name: Run Katana and scripts
        env: 
          KATANA_ACCOUNT_ADDRESS: ${{ secrets.KATANA_ACCOUNT_ADDRESS }}
          KATANA_PRIVATE_KEY: ${{ secrets.KATANA_PRIVATE_KEY }}
        run: bash scripts/katana.sh
