name: Run scripts

on: pull_request

jobs:
  run_scripts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pragma-deployer
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Starknet Devnet RS
      run: |
        wget https://github.com/0xSpaceShard/starknet-devnet-rs/releases/download/v0.1.2/starknet-devnet-aarch64-unknown-linux-gnu.tar.gz
        tar -xvf starknet-devnet-aarch64-unknown-linux-gnu.tar.gz
        chmod +x starknet-devnet
        sudo mv starknet-devnet /usr/local/bin/
        rm -rf starknet-devnet starknet-devnet-aarch64-unknown-linux-gnu.tar.gz
    
    - name: Make script executable
      run: chmod +x scripts/devnet.sh
    
    - name: Set up Python and install Poetry
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: pip install poetry
    
    - name: Install dependencies
      run: poetry install
    
    - name: Set up Scarb
      uses: software-mansion/setup-scarb@v1
    
    - name: Build with Scarb
      run: scarb build
    
    - name: Run Starknet Devnet and scripts
      env:
        KATANA_ACCOUNT_ADDRESS: ${{ secrets.KATANA_ACCOUNT_ADDRESS }}
        KATANA_PRIVATE_KEY: ${{ secrets.KATANA_PRIVATE_KEY }}
        DEVNET_ACCOUNT_ADDRESS: ${{ secrets.KATANA_ACCOUNT_ADDRESS }}
        DEVNET_PRIVATE_KEY: ${{ secrets.KATANA_PRIVATE_KEY }}
      run: bash scripts/devnet.sh
